### ISSUE TITLE
I found erroneous tweet 

### ISSUE THREAD

**Issue by westerdaled** [andikrueger/TweetDeckSPFxFilter#5]
This passed through the filter when I posted into a TweetDeck column search header:

[erroneous tweet from Cinema Arcana](https://twitter.com/CinemaArcana/status/1088232844734943232)

**Comment by andikrueger** [comment]
Thank you for the feedback. Currently there is a limitation of 500 characters for our filter string. We are looking into option how to get around this issue. For more details see #4

**Comment by andikrueger** [comment]
As there is no proper solution for getting around the 500 character limit, we will have to stand some unrelated tweets.

Thanks for reporting.
